spring.application.name=spelltrade

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.table=flyway_schema_history_api

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}